name = "gnatremote"
description = "Gnatstudio remote utility"
version = "0.1.0-dev"

authors = ["Stéphane Rivière"]
maintainers = ["Sowebio SARL <development@soweb.io>"]
maintainers-logins = ["github-username"]
licenses = "GPL-3.0-or-later"
website = "https://www.soweb.io"
tags = []

executables = ["bin/gnatremote"]

[[depends-on]]
gnatcoll = "^24.0.0"

